import { Router } from "express";
import { authRouter } from "../modules/auth/auth.routes";
import { catalogRouter } from "../modules/catalog/catalog.routes";
import { conversationsRouter } from "../modules/conversations/conversations.routes";
import { disputesRouter } from "../modules/disputes/disputes.routes";
import { healthRouter } from "../modules/health/health.routes";
import { jobsRouter } from "../modules/jobs/jobs.routes";
import { listingsRouter } from "../modules/listings/listings.routes";
import { listingsAdminRouter } from "../modules/listings/listings.admin.routes";
import { mediaRouter } from "../modules/media/media.routes";
import { notificationsRouter } from "../modules/notifications/notifications.routes";
import { ordersRouter } from "../modules/orders/orders.routes";
import { paymentsRouter } from "../modules/payments/payments.routes";
import { questionsRouter } from "../modules/questions/questions.routes";
import { reviewsRouter } from "../modules/reviews/reviews.routes";
import { walletRouter } from "../modules/wallet/wallet.routes";
import { payoutsRouter } from "../modules/wallet/payouts.routes";
import { favoritesRouter } from "../modules/favorites/favorites.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/catalog", catalogRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/listings", listingsRouter);
apiRouter.use("/admin/listings", listingsAdminRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/wallet", walletRouter);
apiRouter.use("/payouts", payoutsRouter);
apiRouter.use("/favorites", favoritesRouter);
apiRouter.use("/conversations", conversationsRouter);
apiRouter.use("/disputes", disputesRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/questions", questionsRouter);
apiRouter.use("/reviews", reviewsRouter);
apiRouter.use("/jobs", jobsRouter);
